remove underline from link variant
EasyPost/easy-ui pull request #1532
Opened 2024-12-13 18:31 UTC by btarver40

## 📝 Changes

Please provide a brief summary of the changes made and why they were made.

Include any notes, screenshots, or videos that may be helpful for developers reviewing this pull request.

## ✅ Checklist

Easy UI has certain UX standards that must be met. In general, non-trivial changes should meet the following criteria:

- [ ] Visuals match Design Specs in Figma
- [ ] Stories accompany any component changes
- [ ] Code is in accordance with our style guide
- [ ] Design tokens are utilized
- [ ] Unit tests accompany any component changes
- [ ] TSDoc is written for any API surface area
- [ ] Specs are up-to-date
- [ ] Console is free from warnings
- [ ] No accessibility violations are reported
- [ ] Cross-browser check is performed (Chrome, Safari, Firefox)
- [ ] Changeset is added

~Strikethrough~ any items that are not applicable to this pull request.

2024-12-13 20:51 UTC, Brattin11 reviewed
Looks fine to me,  are there any stories, etc. that need to be updated?

2024-12-17 15:52 UTC, stephenjwatkins requested changes
after thinking about this more and looking at the surface area of current `link` usage in our code i think it'd be best to make this a new variant instead of modifying the `link` variant.

in the design system it's called `Text` (`Button style=Text`), so we could make a new `text` variant for `Button` that is the same styles and code as the `link` variant but without the underline, and leave the `link` variant untouched.

2024-12-20 18:53 UTC, Brattin11 submitted a review, later dismissed
LGTM, could you change the PR title to match what is happening in the code?

2024-12-20 19:39 UTC, stephenjwatkins requested changes

2024-12-20 19:39 UTC, stephenjwatkins commented on easy-ui-react/src/Button/Button.module.scss
>  .variantLink {
```suggestion
.variantLink,
.variantText {
```

2025-01-02 16:08 UTC, stephenjwatkins approved these changes

2025-01-06 17:22 UTC, merged